- include: system.yml
- include: nginx.yml
- meta: flush_handlers # nginx has to be restarted right now if it has to

- include: domain_single.yml
  with_items: "{{ acme_domains }}"

- include: domain_multi.yml
  with_items: "{{ acme_multi_domains }}"

- name: Setup nginx reload cronjob
  cron:
    name: "acme-nginx: Reload nginx"
    job: "service nginx reload"
    hour: 2
    minute: 0
    day: "*"
    user: "root"
  when: acme_cron_renewal_reload
